development:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
#   adapter: mysql
#   host: 192.168.6.66
#   database: pps
#   username: tbq
#   password: tbq
#   encoding: utf8

test:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000

production:
  adapter: sqlite3
  database: db/development.sqlite3
  timeout: 5000
